# .pre-commit-config.yaml
default_stages: [commit]
repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.77.0
    hooks:
      - id: terraform_fmt
      - id: terraform_tflint
      - id: terraform_docs
      - id: terraform_validate
        exclude: "/modules/[^/]+$"
        args:
          - --hook-config=--retry-once-with-cleanup=true
  - repo: https://github.com/bridgecrewio/checkov.git # Keep this config in sync with .github/workflows/terraform.yml
    rev: 2.3.3
    hooks:
      - id: checkov
        verbose: false
        args: [--download-external-modules, "true", --quiet, --compact, --skip-check, CKV2_GHA_1, CKV_AWS_124, CKV_AWS_272, CKV_AWS_273]
