---
name: Terraform

on:
  pull_request:

permissions:
  contents: write
  pull-requests: write

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Format
        id: fmt
        run: terraform fmt -check

      - name: Terraform Init
        id: init
        run: terraform -chdir=examples/basic init

      - name: Terraform Validate
        id: validate
        run: terraform -chdir=examples/basic validate -no-color
        env:
          AWS_DEFAULT_REGION: eu-west-1

  terraform-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Render terraform docs inside the README.md and push changes back to PR branch
        uses: terraform-docs/gh-actions@v1.0.0
        with:
          args: --sort-by required
          git-commit-message: Update module usage (terraform-docs)
          git-push: true
          output-file: README.md
          output-method: inject
          recursive: true
          recursive-path: examples
        continue-on-error: true # added this to prevent a PR from a remote fork failing the workfloww

  tfsec:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Terraform security scan
        uses: aquasecurity/tfsec-action@v1.0.3
        with:
          github_token: ${{ github.token }}
          soft_fail: false
          tfsec_args: --concise-output --force-all-dirs

      - name: Terraform pr commenter
        uses: aquasecurity/tfsec-pr-commenter-action@v1.3.1
        with:
          github_token: ${{ github.token }}
          tfsec_args: --concise-output --force-all-dirs

  checkov:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Run Checkov
        uses: bridgecrewio/checkov-action@v12.2128.0 # checkov-action v12.2128.0 == checkov 2.3.10 - Keep this config in sync with .pre-commit-config.yaml
        with:
          container_user: 1000
          directory: "/"
          download_external_modules: true
          framework: terraform
          output_format: sarif
          quiet: true
          skip_check: CKV_AWS_124,CKV_AWS_272,CKV_AWS_273
          soft_fail: false

  linelint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Linelint
        uses: fernandrone/linelint@0.0.4
